#page title
page_title                                : Tubo - ChatGPT in mobile                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6445877293                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/app/id6445877293                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.vau.studio.bot.open_chat_app                                          # Enter Google Play Store URL.
# presskit_download_link                    : https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/icon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Tubo - AI Assistant                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : ChatGPT on mobile. Smart & Fast & Highly Customized

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Jimmy                                
your_link                                 : https://github.com/lau1944                    
your_city                                 : New York                             
email_address                             : apphunt.team@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : lau1944
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Smart ChatBot
    description                           : Powered by ChatGPT turbo 3. You can ask anything, chatbot will give you answers.
    fontawesome_icon_name                 : comments
    
  - title                                 : Code completion
    description                           : Answer any coding question with code example, make developers life easier.
    fontawesome_icon_name                 : code

  - title                                 : Translation
    description                           : Translate any language like a human.
    fontawesome_icon_name                 : magic


  - title                                 : AI Writer
    description                           : Can write anything for me. Your essay, articles, emial reply, etc.
    fontawesome_icon_name                 : info-circle


# Theme Settings
topbar_color                              : "#333541"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : 
cover_overlay_color                       : "#333541"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#333541"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#ffffff"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#6abd73"
feature_icons_background_color            : "#000000"

social_icons_foreground_color             : "#ffffff"
social_icons_background_color             : "#ffffff"

footer_text_color                         : "#ffffff"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
